[package]
name = "yew-gh-pages"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
gloo = "0.11"
js-sys = "0.3"
wasm-bindgen = "0.2"

[dependencies.yew]
version = "0.21"
features = ["csr"]
